[package]
name = "rdg"
version = "0.1.0"
authors = ["cetusDownfall <34458545+cetusDownfall@users.noreply.github.com>"]

[dependencies]
piston_window = "0.74.0"
piston2d-opengl_graphics = "0.50.0"
piston2d-sprite = "0.41.0"
piston-ai_behavior = "0.22.0"
rand = "0.4.2"
fnv = "1.0.6"

