[package]
name = "block"
version = "0.1.0"
authors = ["cetusDownfall <34458545+cetusDownfall@users.noreply.github.com>"]

[dependencies]
piston_window = "0.74.0"
clagger = {path = "C:/Users/okada/Documents/GitHub/clagger"}
